spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vscpebd?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  data:
    jdbc:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  codec:
    max-in-memory-size: 16777216
logging:
  level:
    org.ventura.cpe.publicador: DEBUG
  pattern:
    file: "%p %c{1.} [%t] %m%n"