DELIMITER $$
CREATE PROCEDURE `bpvs_FE_Correlativo_Baja` () 

BEGIN
DECLARE crs INT DEFAULT 0;

DECLARE DateTimeInt VARCHAR(50);
DECLARE iid INT DEFAULT 0;
DECLARE iserie VARCHAR(50);
DECLARE filas INT DEFAULT 0;



SET @DateTimeInt = DATE_FORMAT(CURRENT_DATE,'%Y%m%d');
SET @iid = (SELECT IFNULL(MAX(ID),0)+1 FROM TRANSACCION_BAJA WHERE fecha= DATE_FORMAT(CURRENT_DATE,'%Y%m%d'));
IF(@iid=1) THEN 
SET @iserie = (SELECT  CONCAT('RA','-', CAST(@DateTimeInt AS CHAR(50)),'-',RIGHT(CONCAT('00000',LTRIM(RTRIM(1))),5)));
UPDATE TRANSACCION_BAJA SET ID=@iid,serie=@iserie WHERE fecha=DATE_FORMAT(CURRENT_DATE,'%Y%m%d');
SELECT @iid,@iserie;
ELSE
SET @iserie = (SELECT  CONCAT('RA','-', CAST(@DateTimeInt AS CHAR(50)),'-',RIGHT(CONCAT('00000',LTRIM(RTRIM(@iid))),5)));
UPDATE TRANSACCION_BAJA SET ID=@iid,serie=@iserie WHERE fecha=DATE_FORMAT(CURRENT_DATE,'%Y%m%d');
SELECT @iid,@iserie;
END IF;

END $$

DELIMITER ;