package ventura.soluciones.sunatwsfe.client.production.service;

import org.apache.log4j.Logger;
import org.ventura.utilidades.entidades.VariablesGlobales;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.4 2016-08-23T09:13:38.713-05:00
 * Generated source version: 3.1.4
 */
@WebServiceClient(name = "billService",
        wsdlLocation = "https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl",
        targetNamespace = "http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/")
public class BillService_Service extends Service {

    private static final Logger logger = Logger.getLogger(BillService_Service.class);

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "billService");

    public final static QName BillServicePort = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort");

    /**
     * Instances default URL for WS.
     */
    static {
        URL url = null;
        try {
            URL baseURL = ventura.soluciones.sunatwsfe.client.production.service.BillService_Service.class.getResource(".");
            url = new URL(baseURL, VariablesGlobales.rutaSunatWebservice);
        } catch (MalformedURLException e) {
            logger.error("static() Can not initialize the default wsdl from 'https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl'");
            logger.error("static() MalformedURLException -->" + e.getMessage());
        }
        WSDL_LOCATION = url;
    }

    public BillService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service(URL) URL Test-WS: " + wsdlLocation);
        }
    }

    public BillService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service() URL Test-WS: " + WSDL_LOCATION);
        }
    }

    public BillService_Service() {
        super(WSDL_LOCATION, SERVICE);
        System.out.println("***************************************************************************************************************************************************");
        System.out.println("**"+WSDL_LOCATION+"                                                                                                                              **");
        System.out.println("***************************************************************************************************************************************************");
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service() URL Test-WS: " + WSDL_LOCATION);
        }
    }

    public BillService_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service() URL Test-WS: " + WSDL_LOCATION);
        }
    }

    public BillService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service(WebServiceFeature...) URL Test-WS: " + WSDL_LOCATION);
        }
    }

    public BillService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
        if (logger.isDebugEnabled()) {
            logger.debug("+-BillService_Service(WebServiceFeature...) URL Test-WS: " + WSDL_LOCATION);
        }
    }

    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public ventura.soluciones.sunatwsfe.client.production.service.BillService getBillServicePort() {
        return super.getPort(BillServicePort, ventura.soluciones.sunatwsfe.client.production.service.BillService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     *                 configure on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public ventura.soluciones.sunatwsfe.client.production.service.BillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(BillServicePort, ventura.soluciones.sunatwsfe.client.production.service.BillService.class, features);
    }

}
