spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vscpebd?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
  rsocket:
    server:
      address: localhost
      port: 7000
      transport: tcp
#  liquibase:
#    drop-first: true
#debug: true
logging:
  level:
    org.ventura.cpe.fase: DEBUG
  pattern:
    file: "%p %c{1.} [%t] %m%n"
