//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.11 at 12:14:24 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/01903/v1.3.2#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.etsi.uri._01903.v1_3;
