---
configuracion:
  gestorTiempo:
    tiempo: "10"
  erp:
    servidorLicencias: "DESKTOP-VADAE01:30000"
    tipoServidor: "10"
    tipoConector: "1"
    servidorBD: "DESKTOP-VADAE01"
    baseDeDatos: "SBO_FACTURACION"
    user: "sa"
    password: "B1Admin"
    erpUser: "manager"
    erpPass: "SBOvent1"
    erpRutaArchivos: "D:\\ERParchivos"
    erpNombreSociedad: ""
  usoSunat:
    ws: "true"
    pdf: "true"
    validacion: "true"
  repositorio:
    tipoServidor: "11"
    servidorBD: "localhost"
    puerto: "3306"
    baseDatos: "vscpebd2"
    user: "ppp"
    password: "ppp"
  proxy:
    usarProxy: "false"
    servidor: ""
    puerto: ""
    requAuth: "false"
    user: ""
    pass: ""
  directorio:
    adjuntos: "C:\\VSCPE\\FE_Ventura\\Transacciones"
  tiempos:
    rqTimeOut: "61"
    rqInterval: "20"
    rsTimeOut: "61"
    rsInterval: "20"
  webService:
    wsUsuario: "admin"
    wsClave: "ventura"
    wsLocation: "http://portal/"
    wsTiempoEsperaPublic: 61
    wsIntervaloRepeticionPublic: 20
    wsTiempoPublicacionPublic: 0
  emisorElectronico:
    rs: "205454844881/SUNAT"
    senderLogo: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\COMPANY_LOGO.jpg"
  impresion:
    pdf: "Codigo QR"
  certificadoDigital:
    rutaCertificado: "D:\\certificado\\CERTIFICATE_TEST.pfx"
    passwordCertificado: "1234"
    proveedorKeystore: "SunJSSE"
    tipoKeystore: "Pkcs12"
  pfeConnector:
    tipo: "2"
  resumenDiario:
    hora: "18:54"
    fecha: ""
  general:
    puertoConfigurador: "7000"
    puertoRequest: "7001"
    puertoResponse: "7002"
    puertoResumen: "7003"
    puertoPublicador: "7004"
    puertoExtractor: ""
  sunat:
    mostrarSoap: "true"
    clienteSunat: "test"
    ambiente: "2"
    usuario:
      usuarioSol: "20510910517MODDATOS"
      claveSol: "moddatos"
    integracionWS: "CONOSE"
    rutaSunatTest: "https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService?wsdl"
    rutaSunatProd: "https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService?wsdl"
    rutaOseTest: "https://proy.ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl"
    rutaOseProd: "https://ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl"
  versionUBL:
    factura: "21"
    boleta: "21"
    notaCredito: "21"
    notaDebito: "21"
  pdf:
    invoiceReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\invoiceDocument.jrxml"
    boletaReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\boletaDocument.jrxml"
    creditNoteReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\creditNoteDocument.jrxml"
    perceptionReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\perceptionDocument.jrxml"
    retentionReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\retentionDocument.jrxml"
    debitNoteReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\debitNoteDocument.jrxml"
    legendSubReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\legendReport.jasper"
    remissionGuideReportPath: "C:\\Users\\ntorres\\Desktop\\DENUEVO\\Recursos\\PdfPlantilla\\\
      Template_Default\\remissionguideDocument.jrxml"
