package org.ventura.soluciones.sunatws_ose.tci.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-15T10:28:16.438-05:00
 * Generated source version: 3.3.2
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({pe.gob.sunat.service.ose_tci.ObjectFactory.class})
public interface BillService {

    @WebMethod(action = "urn:sendBill")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendBillResponse")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    public byte[] sendBill(

            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );

    @WebMethod(action = "urn:getStatus")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.GetStatusResponse")
    @WebResult(name = "status", targetNamespace = "")
    public pe.gob.sunat.service.ose_tci.StatusResponse getStatus(

            @WebParam(name = "ticket", targetNamespace = "")
                    java.lang.String ticket
    );

    @WebMethod(action = "urn:sendSummary")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendSummaryResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendSummary(

            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );

    @WebMethod(action = "urn:sendPack")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.SendPackResponse")
    @WebResult(name = "ticket", targetNamespace = "")
    public java.lang.String sendPack(

            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );

    @WebMethod(action = "urn:getStatusCdr")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.ose_tci.GetStatusCdrResponse")
    @WebResult(name = "status", targetNamespace = "")
    public pe.gob.sunat.service.ose_tci.CdrStatusResponse getStatusCdr(

            @WebParam(name = "rucComprobante", targetNamespace = "")
                    java.lang.String rucComprobante,
            @WebParam(name = "tipoComprobante", targetNamespace = "")
                    java.lang.String tipoComprobante,
            @WebParam(name = "serieComprobante", targetNamespace = "")
                    java.lang.String serieComprobante,
            @WebParam(name = "numeroComprobante", targetNamespace = "")
                    java.lang.Integer numeroComprobante
    );
}
