package org.ventura.soluciones.sunatwsfe.client.test.service;

import pe.gob.sunat.serviceFE.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-08-23T15:43:44.219-05:00
 * Generated source version: 3.1.4
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendSummary")
    @WebMethod(action = "urn:sendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendSummaryResponse")
    public java.lang.String sendSummary(
            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );

    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendBill")
    @WebMethod(action = "urn:sendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendBillResponse")
    public byte[] sendBill(
            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );

    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.GetStatus")
    @WebMethod(action = "urn:getStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.GetStatusResponse")
    public pe.gob.sunat.serviceFE.StatusResponse getStatus(
            @WebParam(name = "ticket", targetNamespace = "")
                    java.lang.String ticket
    );

    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendPack")
    @WebMethod(action = "urn:sendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.serviceFE.SendPackResponse")
    public java.lang.String sendPack(
            @WebParam(name = "fileName", targetNamespace = "")
                    java.lang.String fileName,
            @WebParam(name = "contentFile", targetNamespace = "")
                    javax.activation.DataHandler contentFile
    );
}
