package org.ventura.cpe.core.ws.ose.tci;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebService(name = "billService", targetNamespace = "http://service.sunat.gob.pe")
@XmlSeeAlso({ObjectFactory.class})
public interface BillService {

    /**
     * @param ticket
     * @return returns org.ventura.cpe.core.ws.ose.tci.StatusResponse
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.GetStatusResponse")
    public StatusResponse getStatus(@WebParam(name = "ticket", targetNamespace = "") String ticket);

    /**
     * @param rucComprobante
     * @param serieComprobante
     * @param numeroComprobante
     * @param tipoComprobante
     * @return returns org.ventura.cpe.core.ws.ose.tci.CdrStatusResponse
     */
    @WebMethod(action = "urn:getStatusCdr")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.GetStatusCdrResponse")
    public CdrStatusResponse getStatusCdr(@WebParam(name = "rucComprobante", targetNamespace = "") String rucComprobante,
                                          @WebParam(name = "tipoComprobante", targetNamespace = "") String tipoComprobante,
                                          @WebParam(name = "serieComprobante", targetNamespace = "") String serieComprobante,
                                          @WebParam(name = "numeroComprobante", targetNamespace = "") Integer numeroComprobante);

    /**
     * @param fileName
     * @param contentFile
     * @return returns java.lang.String
     */
    @WebMethod(action = "urn:sendPack")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendPackResponse")
    public String sendPack(@WebParam(name = "fileName", targetNamespace = "") String fileName,
                           @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

    /**
     * @param fileName
     * @param contentFile
     * @return returns byte[]
     */
    @WebMethod(action = "urn:sendBill")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendBillResponse")
    public byte[] sendBill(@WebParam(name = "fileName", targetNamespace = "") String fileName,
                           @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

    /**
     * @param fileName
     * @param contentFile
     * @return returns java.lang.String
     */
    @WebMethod(action = "urn:sendSummary")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "org.ventura.cpe.core.ws.ose.tci.SendSummaryResponse")
    public String sendSummary(@WebParam(name = "fileName", targetNamespace = "") String fileName,
                              @WebParam(name = "contentFile", targetNamespace = "") DataHandler contentFile);

}
