package org.ventura.cpe.core.ws.ose.tci;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "billService", targetNamespace = "http://service.sunat.gob.pe", wsdlLocation = "https://proy.ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl")
public class BillService_Service extends Service {

    private final static URL BILLSERVICE_WSDL_LOCATION;

    private final static WebServiceException BILLSERVICE_EXCEPTION;

    private final static QName BILLSERVICE_QNAME = new QName("http://service.sunat.gob.pe", "billService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://proy.ose.tci.net.pe/ol-ti-itcpe-2/ws/billService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLSERVICE_WSDL_LOCATION = url;
        BILLSERVICE_EXCEPTION = e;
    }

    public BillService_Service() {
        super(__getWsdlLocation(), BILLSERVICE_QNAME);
    }

    public BillService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLSERVICE_QNAME, features);
    }

    public BillService_Service(URL wsdlLocation) {
        super(wsdlLocation, BILLSERVICE_QNAME);
    }

    public BillService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLSERVICE_QNAME, features);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLSERVICE_EXCEPTION != null) {
            throw BILLSERVICE_EXCEPTION;
        }
        return BILLSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort() {
        return super.getPort(new QName("http://service.sunat.gob.pe", "BillServicePort"), BillService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public BillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sunat.gob.pe", "BillServicePort"), BillService.class, features);
    }

}
