
package org.tempuri;

import org.ventura.soluciones.commons.exception.ConfigurationException;
import org.ventura.wsclient.config.ApplicationConfiguration;
import org.ventura.wsclient.config.configuration.Configuracion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "billService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://test.conose.pe/ol-ti-itcpe/billService.svc?wsdl")
@WebServiceClient(name = "billService", targetNamespace = "http://tempuri.org/", wsdlLocation = "")
public class BillService
    extends Service
{

    private final static URL BILLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLSERVICE_EXCEPTION;
    private final static QName BILLSERVICE_QNAME = new QName("http://tempuri.org/", "billService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("https://test.conose.pe/ol-ti-itcpe/billService.svc?wsdl");
            String direccion = (ApplicationConfiguration.getInstance().getConfiguration().getSunat().getClienteSunat().contains("test") ? ApplicationConfiguration.getInstance().getConfiguration().getSunat().getRutaConoseTest() : ApplicationConfiguration.getInstance().getConfiguration().getSunat().getRutaConoseProd());
            url = new URL(direccion);
            System.out.println("Direccion CONOSE WS: "+direccion);
        } catch (MalformedURLException | ConfigurationException ex) {
            e = new WebServiceException(ex);
        }
        BILLSERVICE_WSDL_LOCATION = url;
        BILLSERVICE_EXCEPTION = e;
    }

    public BillService() {
        super(__getWsdlLocation(), BILLSERVICE_QNAME);
    }

    public BillService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLSERVICE_QNAME, features);
    }

    public BillService(URL wsdlLocation) {
        super(wsdlLocation, BILLSERVICE_QNAME);
    }

    public BillService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLSERVICE_QNAME, features);
    }

    public BillService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IbillService
     */
    @WebEndpoint(name = "BillServicePort")
    public IbillService getBillServicePort() {
        return super.getPort(new QName("http://tempuri.org/", "BillServicePort"), IbillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IbillService
     */
    @WebEndpoint(name = "BillServicePort")
    public IbillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BillServicePort"), IbillService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLSERVICE_EXCEPTION!= null) {
            throw BILLSERVICE_EXCEPTION;
        }
        return BILLSERVICE_WSDL_LOCATION;
    }

}
