
package org.tempuri;

import ventura.soluciones.sunatws_ose.tci.consumer.Consumer;
import pe.gob.sunat.service.conose.ObjectFactory;
import pe.gob.sunat.service.conose.StatusCdrResponse;
import pe.gob.sunat.service.conose.StatusResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IbillService", targetNamespace = "http://service.sunat.gob.pe")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IbillService {


    /**
     * 
     * @param fileName
     * @param contentFile
     * @param partyType
     * @return
     *     returns java.lang.String
     * @throws IbillServiceSendSummaryMessageFaultMessage
     */
    @WebMethod(action = "urn:sendSummary")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendSummaryResponse")
    public String sendSummary(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        byte[] contentFile,
        @WebParam(name = "partyType", targetNamespace = "")
        String partyType)
        throws IbillServiceSendSummaryMessageFaultMessage
    ;

    /**
     * 
     * @param ticket
     * @return
     *     returns pe.gob.sunat.service.conose.StatusResponse
     * @throws IbillServiceGetStatusMessageFaultMessage
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.GetStatusResponse")
    public StatusResponse getStatus(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket)
        throws IbillServiceGetStatusMessageFaultMessage
    ;

    /**
     * 
     * @param fileName
     * @param contentFile
     * @return
     *     returns java.lang.String
     * @throws IbillServiceSendPackMessageFaultMessage
     */
    @WebMethod(action = "urn:sendPack")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendPackResponse")
    public String sendPack(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        byte[] contentFile)
        throws IbillServiceSendPackMessageFaultMessage
    ;

    /**
     * 
     * @param rucComprobante
     * @param serieComprobante
     * @param numeroComprobante
     * @param tipoComprobante
     * @return
     *     returns pe.gob.sunat.service.conose.StatusCdrResponse
     * @throws IbillServiceGetStatusCdrMessageFaultMessage
     */
    @WebMethod(action = "urn:getStatusCdr")
    @WebResult(name = "statusCdr", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCdr", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.GetStatusCdr")
    @ResponseWrapper(localName = "getStatusCdrResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.GetStatusCdrResponse")
    public StatusCdrResponse getStatusCdr(
        @WebParam(name = "rucComprobante", targetNamespace = "")
        String rucComprobante,
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        String tipoComprobante,
        @WebParam(name = "serieComprobante", targetNamespace = "")
        String serieComprobante,
        @WebParam(name = "numeroComprobante", targetNamespace = "")
        int numeroComprobante)
        throws IbillServiceGetStatusCdrMessageFaultMessage
    ;

    /**
     * 
     * @param fileName
     * @param contentFile
     * @return
     *     returns byte[]
     * @throws IbillServiceSendBillMessageFaultMessage
     */
    @WebMethod(action = "urn:sendBill")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.conose.SendBillResponse")
    public byte[] sendBill(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "")
        byte[] contentFile)
        throws IbillServiceSendBillMessageFaultMessage
    ;
    @WebMethod(exclude=true)
    void setConsumer(Consumer consumer);

    @WebMethod(exclude=true)
    Consumer getConsumer();

}
