package ventura.soluciones.sunatws.cpr.client.production.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-04-29T09:53:51.682-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "billService", 
                  wsdlLocation = "https://www.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService?wsdl",
                  targetNamespace = "http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/") 
public class BillService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "billService");
    public final static QName BillServicePort = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort");
    public final static QName BillServicePort1 = new QName("http://service.gem.factura.comppago.registro.servicio.sunat.gob.pe/", "BillServicePort.1");
    static {
        URL url = null;
        try {
            url = new URL("https://www.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://www.sunat.gob.pe/ol-ti-itemision-otroscpe-gem/billService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BillService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BillService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public ventura.soluciones.sunatws.cpr.client.production.service.BillService getBillServicePort() {
        return super.getPort(BillServicePort, ventura.soluciones.sunatws.cpr.client.production.service.BillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServicePort")
    public ventura.soluciones.sunatws.cpr.client.production.service.BillService getBillServicePort(WebServiceFeature... features) {
        return super.getPort(BillServicePort, ventura.soluciones.sunatws.cpr.client.production.service.BillService.class, features);
    }


    /**
     *
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServicePort.1")
    public ventura.soluciones.sunatws.cpr.client.production.service.BillService getBillServicePort1() {
        return super.getPort(BillServicePort1, ventura.soluciones.sunatws.cpr.client.production.service.BillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillServicePort.1")
    public ventura.soluciones.sunatws.cpr.client.production.service.BillService getBillServicePort1(WebServiceFeature... features) {
        return super.getPort(BillServicePort1, ventura.soluciones.sunatws.cpr.client.production.service.BillService.class, features);
    }

}
