package org.ventura.soluciones.sunatws.client.production.service;

import pe.gob.sunat.service.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-09-15T08:17:20.817+02:00
 * Generated source version: 3.0.5
 */
@WebService(targetNamespace = "http://service.sunat.gob.pe", name = "billService")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface BillService {

    /**
     * This method sent an Invoice, Boleta, Credit Note or Debit Note to Sunat WS.
     *
     * @param fileName    The name of attachment file.
     * @param contentFile The ZIP attachment file.
     * @return Returns the CDR response by Sunat.
     */
    @WebMethod(action = "urn:sendBill")
    @WebResult(name = "applicationResponse", targetNamespace = "")
    @RequestWrapper(localName = "sendBill", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBill")
    @ResponseWrapper(localName = "sendBillResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendBillResponse")
    public byte[] sendBill(@WebParam(name = "fileName", targetNamespace = "") String fileName, @WebParam(name = "contentFile", targetNamespace = "") javax.activation.DataHandler contentFile);

    /**
     * This method sent an Voided Document or Summary document to Sunat WS.
     *
     * @param fileName    The name of attachment file.
     * @param contentFile The ZIP attachment file.
     * @return Returns the ticket response.
     */
    @WebMethod(action = "urn:sendSummary")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendSummary", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummary")
    @ResponseWrapper(localName = "sendSummaryResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendSummaryResponse")
    public String sendSummary(@WebParam(name = "fileName", targetNamespace = "") String fileName, @WebParam(name = "contentFile", targetNamespace = "") javax.activation.DataHandler contentFile);

    /**
     * This method sent a document to Sunat WS.
     *
     * @param fileName    The name of attachment file.
     * @param contentFile The ZIP attachment file.
     * @return Returns the ticket response.
     */
    @WebMethod(action = "urn:sendPack")
    @WebResult(name = "ticket", targetNamespace = "")
    @RequestWrapper(localName = "sendPack", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPack")
    @ResponseWrapper(localName = "sendPackResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.SendPackResponse")
    public String sendPack(@WebParam(name = "fileName", targetNamespace = "") String fileName, @WebParam(name = "contentFile", targetNamespace = "") javax.activation.DataHandler contentFile);

    /**
     * This method sent a ticket to Sunat WS.
     *
     * @param ticket The ticket of request.
     * @return Returns an object than contains the response code an the CDR response.
     */
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatus")
    @WebMethod(action = "urn:getStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://service.sunat.gob.pe", className = "pe.gob.sunat.service.GetStatusResponse")
    public pe.gob.sunat.service.StatusResponse getStatus(@WebParam(name = "ticket", targetNamespace = "") String ticket);

} //BillService
